# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version"
                required: true
                default: "0.0.0"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              env:
                  VERSION: ${{ github.event.inputs.version }}
              run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true -c Release /p:Version=$VERSION

            - name: Push
              run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
